STATIONS="${STATIONS} EDDM" # Munich
STATIONS="${STATIONS} EDDN" # Nuremberg
STATIONS="${STATIONS} EDJA" # Memmingen
STATIONS="${STATIONS} EDMA" # Augsburg
STATIONS="${STATIONS} EDMO" # Oberpfaffenhofen

STATIONS="${STATIONS} ETEB" # Ansbach
STATIONS="${STATIONS} ETHA" # Altenstadt
STATIONS="${STATIONS} ETHL" # Laupheim
STATIONS="${STATIONS} ETIH" # Hohenfels
STATIONS="${STATIONS} ETSI" # Ingolstadt Manching
STATIONS="${STATIONS} ETSL" # Lechfeld
STATIONS="${STATIONS} ETSN" # Neuburg

STATIONS="${STATIONS} LOWI" # Insbruck

STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "
STATIONS="${STATIONS} "

